version: "3.7"
services:

# reader server to mongo
  yang:
    build:
      context: .
      dockerfile: yang.dockerfile
    container_name: yang-container 
    image: yang-image
#     networks:
#       - yang-network
    
# networks:
#   yang-network:
#     driver: bridge
#     name: yang-network

































    

