version: "3.7"
services:

# reader server to mongo
  yang:
    image: gcr.io/applytics-303318/yang-image:latest
    container_name: yang-container 
    networks:
      - yinyang-network
#connection to external network
networks:
  yinyang-network:
    external: true







































    

