version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    restart: always
    networks:
      - kafka-network
    #container_name: zookeeper-containers
    # logging:
    #   driver: none

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    expose:
      - "9092"
      - "9093"
    environment:
      
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://10.128.0.4:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://10.128.0.4:9093
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CREATE_TOPICS: "sarama_topic:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
      KAFKA_MESSAGE_MAX_BYTES: 100000000
    volumes:
      - kafka-storage:/var/run/docker.sock
      - kafka-storage:/var/lib/kafka
      #
    networks:
      - kafka-network
    restart: always
    # container_name: kafka-container
    # logging:
    #   driver: none


volumes:
  kafka-storage:
    name: kafka-storage

networks:
  kafka-network:
    driver: bridge
    name: kafka-network
