version: "3.7"
services:

# reader server to mongo
  yang:
    build:
      context: .
      dockerfile: yang.dockerfile
    container_name: yang-container 
    image: yang-image
    networks:
      - yinyang-network

#connection to external network
networks:
  yinyang-network:
    external: true

































    

