name: Deploy
on: [push]



jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: copy production docker-compose file
      uses: appleboy/scp-action@master
      env:
        HOST: 34.71.171.144
        USERNAME: git_bot
        KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
      with:
        source: "docker-compose.yaml"
        target: "kafka"
        
    - name: ssh to instance
      uses: appleboy/ssh-action@master
      with:
        host: 34.71.171.144
        username: git_bot
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        script: cd kafka && sudo docker-compose up -d --force-recreate && sudo docker image prune -f 
