name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker-compose build image
      run: docker-compose build
      
    - name: Check images
      run: docker image ls
    
    - name: Tag image
      run:  docker tag yang-image gcr.io/applytics-303318/yang-image
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
      
    - name: Install gcloud
      run: |
        gcloud auth configure-docker
    
    - name: Push image to google container
      run:  docker push gcr.io/applytics-303318/yang-image
      
    - name: copy production docker-compose file
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.IP }}
        USERNAME:  ${{ secrets.USER }}
        KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
      with:
        source: "docker-compose-production.yaml"
        target: "yang"

    - name: ssh to instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        script: cd yang && sudo docker pull gcr.io/applytics-303318/yang-image:latest && sudo docker-compose -f docker-compose-production.yaml up -d && sudo docker image prune -f
